//  INSURANCE COMPANIES AND PLATE TYPES DATA
export const insuranceList = [
  { label: "Please choose your insurance", value: "" },
  { label: "Al Baraka Insurances", value: "al_baraka" },
  { label: "ASTREE Insurances", value: "astree" },
  { label: "At-Takafulia Insurances", value: "at_takafulia" },
  { label: "BH Insurance", value: "bh" },
  { label: "BIAT Insurances", value: "biat" },
  { label: "BNA Insurances", value: "bna" },
  { label: "CARTE Insurances", value: "carte" },
  { label: "COMAR Insurances", value: "comar" },
  { label: "CTAMA Insurances", value: "ctama" },
  { label: "GAT Insurances", value: "gat" },
  { label: "LLOYD Insurances", value: "lloyd" },
  { label: "MAE Insurances", value: "mae" },
  { label: "MAGHREBIA Insurances", value: "maghrebia" },
  { label: "STAR Insurances", value: "star" },
  { label: "Zitouna Takaful Insurances", value: "zitouna_takaful" },
];

export const plateTypeList = [
  { label: "Type", value: "" },
  { label: "TUN (Tunisie)", value: "tu" },
  { label: "PAT (Personnel administratif et technique)", value: "pat" },
  { label: "CMD (Chef de mission diplomatique)", value: "cmd" },
  { label: "CD (Corps diplomatique)", value: "cd" },
  { label: "MD (Mission diplomatique)", value: "md" },
  { label: "RS (Regime suspensif)", value: "rs" },
  { label: "TRAC (Tracteur agricole)", value: "trac" },
  { label: "REM (Remorque)", value: "rem" },
  { label: "ONU (Organisation nation unies)", value: "onu" },
  { label: "ONG (Organisation non gouvernementale)", value: "ong" },
  { label: "AA (Appareil agricole)", value: "aa" },
  { label: "ES (Engin spécial)", value: "es" },
  { label: "MOTO", value: "moto" },
  { label: "IT (Immatriculation temporaire)", value: "it" },
  { label: "MC (Mission consulaire)", value: "mc" },
  { label: "CC (Corps consulaire)", value: "cc" },
  { label: "WW (Véhicule de l'essai)", value: "ww" },
  { label: "- (Véhicule de l'état)", value: "etat" },
  { label: "Autre", value: "autre" },
];